version: 2.1

jobs:
  test-projectA:
    docker:
      - image: circleci/python:3.7.5
    working_directory: ~/codecov-study
    steps:
      - checkout
      - restore_cache:
          key: projectA-{{ .Branch }}-{{ checksum "~/codecov-study/projectA/Pipfile.lock" }}
      - run:
          name: Test projectA
          command: |
            cd ~/codecov-study/projectA
            pip install pipenv
            pipenv install --dev
            pipenv run pytest --cov=./../ --cov-report=xml
            cd ~/codecov-study
            bash <(curl https://codecov.io/bash)
      - save_cache:
          key: projectA-{{ .Branch }}-{{ checksum "~/codecov-study/projectA/Pipfile.lock" }}
          paths:
            - '~/.local/share/virtualenvs'

  test-projectB:
    docker:
      - image: circleci/python:3.7.5
    working_directory: ~/codecov-study
    steps:
      - checkout
      - restore_cache:
          key: projectB-{{ .Branch }}-{{ checksum "~/codecov-study/projectB/Pipfile.lock" }}
      - run:
          name: Test projectB
          command: |
            cd ~/codecov-study/projectB
            pip install pipenv
            pipenv install --dev
            pipenv run pytest --cov=./../ --cov-report=xml
            cd ~/codecov-study
            bash <(curl https://codecov.io/bash)
      - save_cache:
          key: projectB-{{ .Branch }}-{{ checksum "~/codecov-study/projectB/Pipfile.lock" }}
          paths:
            - '~/.local/share/virtualenvs'

workflows:
  main:
    jobs:
      - test-projectA
      - test-projectB
