version: 2.1

jobs:
  test-projectA:
    # https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/python/images/3.7.5/Dockerfile
    docker:
      - image: circleci/python:3.7.5
    working_directory: ~/codecov-study
    steps:
      - checkout
      - restore_cache:
          key: projectA-{{ .Branch }}-{{ checksum "~/codecov-study/projectA/Pipfile.lock" }}
      - run:
          name: Install dev packages
          command: |
            cd ~/codecov-study/projectA
            pipenv install --dev
      - save_cache:
          key: projectA-{{ .Branch }}-{{ checksum "~/codecov-study/projectA/Pipfile.lock" }}
          paths:
            - '~/.local/share/virtualenvs'
      - run:
          name: Run pycodestyle
          command: |
            cd ~/codecov-study/projectA
            pipenv run pycodestyle .
      - run:
          name: Test projectA
          command: |
            cd ~/codecov-study/projectA
            pipenv run pytest --cov=./../ --cov-report=xml
      - run:
          name: Upload the coverage report
          command: |
            cd ~/codecov-study
            bash <(curl https://codecov.io/bash)

  test-projectB:
    docker:
      - image: circleci/python:3.7.5
    working_directory: ~/codecov-study
    steps:
      - checkout
      - restore_cache:
          key: projectB-{{ .Branch }}-{{ checksum "~/codecov-study/projectB/Pipfile.lock" }}
      - run:
          name: Install dev packages
          command: |
            cd ~/codecov-study/projectB
            pipenv install --dev
      - save_cache:
          key: projectB-{{ .Branch }}-{{ checksum "~/codecov-study/projectB/Pipfile.lock" }}
          paths:
            - '~/.local/share/virtualenvs'
      - run:
          name: Run pycodestyle
          command: |
            cd ~/codecov-study/projectB
            pipenv run pycodestyle .
      - run:
          name: Test projectB
          command: |
            cd ~/codecov-study/projectB
            pipenv run pytest --cov=./../ --cov-report=xml
      - run:
          name: Upload the coverage report
          command: |
            cd ~/codecov-study
            bash <(curl https://codecov.io/bash)

workflows:
  main:
    jobs:
      - test-projectA
      - test-projectB
